(module $Mref_ex
  (type $t (func))
  (func $f) (elem declare func $f)
  (global (export "g-const-funcnull") (ref null func) (ref.null func))
  (global (export "g-const-func") (ref func) (ref.func $f))
  (global (export "g-const-refnull") (ref null $t) (ref.null $t))
  (global (export "g-const-ref") (ref $t) (ref.func $f))
  (global (export "g-const-extern") externref (ref.null extern))
  (global (export "g-var-funcnull") (mut (ref null func)) (ref.null func))
  (global (export "g-var-func") (mut (ref func)) (ref.func $f))
  (global (export "g-var-refnull") (mut (ref null $t)) (ref.null $t))
  (global (export "g-var-ref") (mut (ref $t)) (ref.func $f))
  (global (export "g-var-extern") (mut externref) (ref.null extern))
)

(register "Mref_ex" $Mref_ex)

(module $Mref_im
  (type $t (func))
  (global (import "Mref_ex" "g-const-funcnull") (ref null func))
  (global (import "Mref_ex" "g-const-func") (ref null func))
  (global (import "Mref_ex" "g-const-refnull") (ref null func))
  (global (import "Mref_ex" "g-const-ref") (ref null func))
  (global (import "Mref_ex" "g-const-func") (ref func))
  (global (import "Mref_ex" "g-const-ref") (ref func))
  (global (import "Mref_ex" "g-const-refnull") (ref null $t))
  (global (import "Mref_ex" "g-const-ref") (ref null $t))
  (global (import "Mref_ex" "g-const-ref") (ref $t))
  (global (import "Mref_ex" "g-const-extern") externref)

  (global (import "Mref_ex" "g-var-funcnull") (mut (ref null func)))
  (global (import "Mref_ex" "g-var-func") (mut (ref func)))
  (global (import "Mref_ex" "g-var-refnull") (mut (ref null $t)))
  (global (import "Mref_ex" "g-var-ref") (mut (ref $t)))
  (global (import "Mref_ex" "g-var-extern") (mut externref))
)
