let init () =
  Builtin.Nats.set_wasm_hooks
    ~il_of_num:Construct.il_of_num
    ~il_of_vec:Construct.il_of_vec
    ~sl_to_num:Deconstruct.sl_to_num
    ~sl_to_vec:Deconstruct.sl_to_vec
    ~sl_to_testop:Deconstruct.sl_to_testop
    ~sl_to_relop:Deconstruct.sl_to_relop
    ~sl_to_unop:Deconstruct.sl_to_unop
    ~sl_to_binop:Deconstruct.sl_to_binop
    ~sl_to_cvtop:Deconstruct.sl_to_cvtop
    ~sl_to_vtestop:Deconstruct.sl_to_vtestop
    ~sl_to_vrelop:Deconstruct.sl_to_vrelop
    ~sl_to_vunop:Deconstruct.sl_to_vunop
    ~sl_to_vbinop:Deconstruct.sl_to_vbinop
    ~sl_to_vternop:Deconstruct.sl_to_vternop
    ~sl_to_vcvtop:Deconstruct.sl_to_vcvtop
    ~sl_to_vshiftop:Deconstruct.sl_to_vshiftop
    ~sl_to_vbitmaskop:Deconstruct.sl_to_vbitmaskop
    ~sl_to_vvtestop:Deconstruct.sl_to_vvtestop
    ~sl_to_vvunop:Deconstruct.sl_to_vvunop
    ~sl_to_vvbinop:Deconstruct.sl_to_vvbinop
    ~sl_to_vvternop:Deconstruct.sl_to_vvternop
    ~sl_to_vsplatop:Deconstruct.sl_to_vsplatop
    ~sl_to_vextractop:Deconstruct.sl_to_vextractop
    ~sl_to_vreplaceop:Deconstruct.sl_to_vreplaceop
    ~sl_to_loadop:Deconstruct.sl_to_loadop
    ~sl_to_storeop:Deconstruct.sl_to_storeop
    ~sl_to_vec_loadop:Deconstruct.sl_to_vec_loadop
    ~sl_to_vec_storeop:Deconstruct.sl_to_vec_storeop
    ~sl_to_vec_laneop:Deconstruct.sl_to_vec_laneop
